# @github/sarathsprakash
# TODO, create different network for each components

version: "3.7"

services:
  stream_db:
    image: mysql:5.7
    command: mysqld --user=root --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: altv
      MYSQL_USER: altv_user
      MYSQL_PASSWORD: altv_pwd
    expose:
      - 3306
    volumes:
      - "./stream/db/schema.sql:/docker-entrypoint-initdb.d/01.sql:ro"
      - "./stream/db/data.sql:/docker-entrypoint-initdb.d/02.sql:ro"

  rabbit:
    image: rabbitmq:3.8-management
    ports:
        - "15673:15672"
    restart: always

  frontend:
    build: ./frontend
    restart: always
    expose:
      - 8080
    environment:
      DEBUG: 1
    depends_on:
      - rabbit
      - nginx
  
  # A dummy service, TODO:
  # session:
  #   build: ./session
  #   restart: always

  stream:
    build: ./stream
    restart: always
    depends_on:
      - rabbit
      - stream_db
    environment:
      RABBIT_USER: guest
      RABBIT_PASSWORD: guest
      RABBIT_HOST: rabbit
      RABBIT_PORT: 5672
      DB_USER: altv_user
      DB_PASSWORD: altv_pwd
      DB_HOST: stream_db
      DB_PORT: 3306
      DB_NAME: altv

  nginx:
    image: nginx:1.19.10
    restart: always
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
