AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:rabbit}:${RABBIT_PORT:5672}/

DB_URIS:
    "stream:Base": mysql+pymysql://${DB_USER:altv_user}:${DB_PASSWORD:altv_pwd}@${DB_HOST:stream_db}:${DB_PORT:3306}/${DB_NAME:altv}